name: NaturePowers
version: '2.0-SNAPSHOT'
main: me.ivan.naturePowers.NaturePowers
api-version: '1.21.4'
commands:
  chooseClass:
    description: "Opens a GUI that let's the player choose their class."

